using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using SmartApp.Application.Common.Interfaces;
using SmartApp.Domain.Catalog;
using SmartApp.Domain.Common;
using SmartApp.Domain.Identity;
using SmartApp.Domain.Tenancy;

namespace SmartApp.Persistence.Context;

/// <summary>
/// The application's EF Core context and the implementation of <see cref="IApplicationDbContext"/>.
///
/// <para>Phase 2 wires the tenant-isolation foundation:</para>
/// <list type="bullet">
///   <item><description>A global query filter is applied to every <see cref="BaseEntity"/> so all reads are scoped to the current tenant and exclude soft-deleted rows.</description></item>
///   <item><description><c>TenantId</c> is stamped server-side on insert (never from the client).</description></item>
///   <item><description>Audit fields and soft-delete conversion are handled by <c>AuditableEntityInterceptor</c> (registered at construction).</description></item>
/// </list>
///
/// <para>
/// No entities/DbSets are declared yet — they are introduced per feature in later phases.
/// Entity type configurations are auto-applied from this assembly, so new entities light up
/// the tenant filter automatically. See SmartApp-Architecture/09-Multi-Tenant.md §6.
/// </para>
/// </summary>
public sealed class AppDbContext : DbContext, IApplicationDbContext
{
    private readonly ITenantProvider _tenantProvider;

    public AppDbContext(DbContextOptions<AppDbContext> options, ITenantProvider tenantProvider)
        : base(options)
    {
        _tenantProvider = tenantProvider;
    }

    // ---- Tenant Core DbSets (Phase 3) ----
    public DbSet<Tenant> Tenants => Set<Tenant>();
    public DbSet<TenantSetting> TenantSettings => Set<TenantSetting>();

    // ---- Identity DbSets (Phase 4) ----
    public DbSet<AppUser> Users => Set<AppUser>();
    public DbSet<AppRole> Roles => Set<AppRole>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();

    // ---- Catalog DbSets (Phase 7) ----
    public DbSet<Category> Categories => Set<Category>();
    public DbSet<Unit> Units => Set<Unit>();
    public DbSet<Brand> Brands => Set<Brand>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<ProductUnit> ProductUnits => Set<ProductUnit>();
    public DbSet<ProductBarcode> ProductBarcodes => Set<ProductBarcode>();
    public DbSet<ProductPrice> ProductPrices => Set<ProductPrice>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Apply all IEntityTypeConfiguration<T> found in this assembly.
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

        // SQL Server-specific check constraints (functions like ISJSON) are applied only when the
        // provider is SQL Server, so SQLite-backed tests are not broken by unsupported functions.
        if (Database.IsSqlServer())
        {
            modelBuilder.Entity<TenantSetting>()
                .ToTable(t => t.HasCheckConstraint(
                    "CK_TenantSettings_Theme_Json",
                    "[ThemeJson] IS NULL OR ISJSON([ThemeJson]) = 1"));

            modelBuilder.Entity<Product>()
                .ToTable(t => t.HasCheckConstraint(
                    "CK_Products_Custom_Json",
                    "[CustomFieldsJson] IS NULL OR ISJSON([CustomFieldsJson]) = 1"));
        }

        bool isSqlServer = Database.IsSqlServer();

        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            // Apply the tenant + soft-delete global query filter to every BaseEntity-derived type.
            if (typeof(BaseEntity).IsAssignableFrom(entityType.ClrType))
            {
                modelBuilder.Entity(entityType.ClrType)
                    .HasQueryFilter(BuildTenantAndSoftDeleteFilter(entityType.ClrType));
            }

            if (!isSqlServer)
            {
                // ROWVERSION is auto-generated by SQL Server. Providers without it (e.g. SQLite in tests)
                // cannot generate the value, so treat the concurrency stamp as an app-managed token there.
                var concurrency = entityType.FindProperty("ConcurrencyStamp");
                if (concurrency is not null)
                {
                    concurrency.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never;
                    concurrency.SetDefaultValue(Array.Empty<byte>());
                }

                // SYSUTCDATETIME() defaults are SQL Server-specific. Drop them on other providers so
                // SQLite-backed tests don't hit an unknown function; the app/interceptor sets the value.
                foreach (var property in entityType.GetProperties())
                {
                    if (property.GetDefaultValueSql() is not null)
                    {
                        property.SetDefaultValueSql(null);
                    }
                }
            }
        }

        ApplyIdentityTenantFilters(modelBuilder);
    }

    /// <summary>
    /// Applies tenant query filters to Identity entities that carry a TenantId but do NOT inherit
    /// <see cref="BaseEntity"/> (nullable-tenant users/tokens, keyless-style join tables). The filter
    /// treats a null current tenant (system-owner / unresolved) as "no restriction", matching the
    /// BaseEntity filter behavior. See SmartApp-Architecture/09-Multi-Tenant.md §6.
    /// </summary>
    private void ApplyIdentityTenantFilters(ModelBuilder modelBuilder)
    {
        // Nullable TenantId (system owner rows have null): visible when unrestricted or matching.
        modelBuilder.Entity<AppUser>().HasQueryFilter(u =>
            _tenantProvider.TenantIdOrNull == null || u.TenantId == _tenantProvider.TenantIdOrNull);

        modelBuilder.Entity<RefreshToken>().HasQueryFilter(rt =>
            _tenantProvider.TenantIdOrNull == null || rt.TenantId == _tenantProvider.TenantIdOrNull);

        // Non-nullable TenantId join tables.
        modelBuilder.Entity<UserRole>().HasQueryFilter(ur =>
            _tenantProvider.TenantIdOrNull == null || ur.TenantId == _tenantProvider.TenantIdOrNull);

        modelBuilder.Entity<RolePermission>().HasQueryFilter(rp =>
            _tenantProvider.TenantIdOrNull == null || rp.TenantId == _tenantProvider.TenantIdOrNull);
    }

    public override int SaveChanges()
    {
        StampTenantId();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        StampTenantId();
        return base.SaveChangesAsync(cancellationToken);
    }

    /// <summary>
    /// Stamps the current tenant id on newly added tenant-owned entities. Never overrides an
    /// explicit id for system-owner operations (which act across tenants).
    /// </summary>
    private void StampTenantId()
    {
        if (_tenantProvider.IsSystemOwner || _tenantProvider.TenantIdOrNull is not long tenantId)
        {
            return;
        }

        foreach (var entry in ChangeTracker.Entries<BaseEntity>())
        {
            if (entry.State == EntityState.Added)
            {
                entry.Entity.TenantId = tenantId;
            }
        }
    }

    /// <summary>
    /// Builds <c>e =&gt; e.TenantId == currentTenant &amp;&amp; !e.IsDeleted</c> for the given entity type.
    /// The tenant id is read through a closure over <see cref="ITenantProvider"/> so it re-evaluates
    /// per request. System-owner requests read <c>TenantIdOrNull == null</c>, which the filter treats
    /// as "no tenant restriction" via the null-guard below.
    /// </summary>
    private LambdaExpression BuildTenantAndSoftDeleteFilter(Type entityClrType)
    {
        // Parameter: (TEntity e)
        ParameterExpression parameter = Expression.Parameter(entityClrType, "e");

        // e.TenantId
        MemberExpression tenantProperty = Expression.Property(parameter, nameof(BaseEntity.TenantId));

        // _tenantProvider.TenantIdOrNull  (captured; evaluated at query time)
        Expression<Func<long?>> currentTenantAccessor = () => _tenantProvider.TenantIdOrNull;
        Expression currentTenant = Expression.Invoke(currentTenantAccessor);

        // Tenant match: (_tenantProvider.TenantIdOrNull == null) || (e.TenantId == _tenantProvider.TenantIdOrNull.Value)
        // The null branch lets system-owner / unresolved contexts bypass the tenant restriction
        // (soft-delete filtering still applies). Cross-tenant reads for normal users are impossible
        // because their TenantIdOrNull is always their own tenant.
        Expression tenantIsNull = Expression.Equal(currentTenant, Expression.Constant(null, typeof(long?)));
        Expression tenantValue = Expression.Property(currentTenant, nameof(Nullable<long>.Value));
        Expression tenantEquals = Expression.Equal(tenantProperty, tenantValue);
        Expression tenantMatch = Expression.OrElse(tenantIsNull, tenantEquals);

        // Soft delete: !e.IsDeleted
        MemberExpression isDeleted = Expression.Property(parameter, nameof(BaseEntity.IsDeleted));
        Expression notDeleted = Expression.Not(isDeleted);

        // Combined: tenantMatch && !e.IsDeleted
        Expression body = Expression.AndAlso(tenantMatch, notDeleted);

        return Expression.Lambda(body, parameter);
    }
}
